<p><font size="6"><b>Python the basics: A quick recap</b></font></p>

> *DS Data manipulation, analysis and visualisation in Python*  
> *December, 2017*

> *© 2016, Joris Van den Bossche and Stijn Van Hoey  (<mailto:jorisvandenbossche@gmail.com>, <mailto:stijnvanhoey@gmail.com>). Licensed under [CC BY 4.0 Creative Commons](http://creativecommons.org/licenses/by/4.0/)*


## First steps

the obligatory...

In [75]:
print("Hello DS_course!") # python 3(!)

Hello DS_course!


Python is a calculator

In [76]:
4*5

20

In [77]:
3**2 # ^ in R

9

In [78]:
(3 + 4)/2, 3 + 4/2, 

(3.5, 5.0)

In [79]:
21//5, 21%5,  # floor division, modulo

(4, 1)

Variable assignment

In [80]:
my_variable_name = 'DS_course'
my_variable_name

'DS_course'

In [81]:
name, age = 'John', 30
print('The age of {} is {:d}'.format(name, age))

The age of John is 30


More information on print format: https://pyformat.info/

## Loading functionalities

In [82]:
import os

In [83]:
os.listdir()

['.ipynb_checkpoints',
 '00-jupyter_introduction.ipynb',
 '01-basic.ipynb',
 '02-control_flow.ipynb',
 '03-functions.ipynb',
 '04-reusing_code.ipynb',
 '05-numpy.ipynb',
 'data',
 'python_rehearsal.ipynb',
 'rehears1.py',
 'rehears2.py',
 '_solutions',
 '__pycache__']

Loading with defined short name (community agreement)

In [84]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Loading functions from any file/module/package:

In [85]:
%%file rehears1.py  
#this writes a file in your directory, check it(!)

"A demo module."

def print_it():
    """Dummy function to print the string it"""
    print('it')

Overwriting rehears1.py


In [86]:
import rehears1

In [87]:
rehears1.print_it()

it


In [88]:
%%file rehears2.py  
#this writes a file in your directory, check it(!)

"A demo module."

def print_it():
    """Dummy function to print the string it"""
    print('it')

def print_custom(my_input):
    """Dummy function to print the string that"""
    print(my_input)

Overwriting rehears2.py


In [89]:
from rehears2 import print_it, print_custom

In [90]:
print_custom('DS_course')

DS_course


<div class="alert alert-danger">
    <b>DON'T</b>: `from os import *`. Just don't!
</div>

## Datatypes

### Numerical

**floats**

In [91]:
a_float = 5.

In [92]:
type(a_float)

float

**integers**

In [93]:
an_integer = 4

In [94]:
type(an_integer)

int

**booleans**

In [95]:
a_boolean = True
a_boolean

True

In [96]:
type(a_boolean)

bool

In [97]:
3 > 4 # results in boolean

False

### Containers

#### Strings

In [98]:
a_string = "abcde"
a_string

'abcde'

In [99]:
a_string.capitalize(), a_string.capitalize(), a_string.endswith('f') #,...

('Abcde', 'Abcde', False)

In [100]:
a_string.upper().replace('B', 'A')

'AACDE'

In [101]:
a_string + a_string

'abcdeabcde'

In [102]:
a_string * 5

'abcdeabcdeabcdeabcdeabcde'

#### Lists

In [108]:
a_list = [1, 'a', 3, 4]

In [109]:
a_list.append(8.2)
a_list

[1, 'a', 3, 4, 8.2]

In [110]:
a_list.reverse()
a_list

[8.2, 4, 3, 'a', 1]

<div class="alert alert-info">
    <b>REMEMBER</b>:  The list is updated in-place; a_list.reverse() does not return anything, it updates the list
</div>

In [111]:
a_list + ['b', 5]

[8.2, 4, 3, 'a', 1, 'b', 5]

In [112]:
[el*2 for el in a_list]  # list comprehensions...a short for-loop

[16.4, 8, 6, 'aa', 2]

In [119]:
[el for el in dir(list) if not el[0]=='_']

['append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [124]:
[el for el in dir(list) if not str.startswith(el, "_")]

['append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

<div class="alert alert-success">
    <b>EXERCISE</b>: Rewrite the previous list comprehension by using a builtin string method to test if the element starts with an underscore
</div>

In [ ]:
# %load _solutions/python_rehearsal35.py

<div class="alert alert alert-success">
    <b>EXERCISE</b>: Given the sentence `the quick brown fox jumps over the lazy dog`, split the sentence in words and put all the word-lengths in a list. 
</div>

In [148]:
sentence = "the quick brown fox jumps over the lazy dog"
sentence_list = str.split(sentence, " ")
sentence.split(" ")
[len(word) for word in sentence.split(sep = " ")]

[3, 5, 5, 3, 5, 4, 3, 4, 3]

In [ ]:
# %load _solutions/python_rehearsal37.py

#### Dictionaries

In [152]:
a_dict = {'a': 1, 'b': 2}

"{'a': 1, 'b': 2}"

In [128]:
a_dict['c'] = 3
a_dict['a'] = 5

In [151]:
a_dict
for a_key, a_value in a_dict.items():
    print(a_key, a_value)

a 5
b 2
c 3


In [130]:
a_dict.keys(), a_dict.values(), a_dict.items()

(dict_keys(['a', 'b', 'c']),
 dict_values([5, 2, 3]),
 dict_items([('a', 5), ('b', 2), ('c', 3)]))

In [131]:
an_empty_dic = dict() # or just {}
an_empty_dic

{}

**tuple**

In [132]:
a_tuple = (1, 2, 4)

<div class="alert alert-info">
    <b>REMEMBER</b>:  (), [], {} => depends from the datatype you want to create!
</div>

In [133]:
collect = a_list, a_dict

In [138]:
print(a_list)
print(a_dict)
type(collect)

[8.2, 4, 3, 'a', 1]
{'a': 5, 'b': 2, 'c': 3}


tuple

In [140]:
serie_of_numbers = 3, 4, 5

In [141]:
# Using tuples on the left-hand side of assignment allows you to extract fields
a, b, c = serie_of_numbers

In [142]:
print(c, b, a)

5 4 3


### Accessing container values

In [153]:
a_string[2:5]

'cde'

In [154]:
a_list[-2]

'a'

In [155]:
a_list = [0, 1, 2, 3]

In [156]:
a_list[:3]

[0, 1, 2]

In [162]:
a_list
a_list[::2]

[0, 2]

<div class="alert alert-success">
    <b>EXERCISE</b>: Reverse the `a_list` without using the built-in reverse method, but using an appropriate slicing command:
</div>

In [ ]:
# %load _solutions/python_rehearsal54.py

In [ ]:
a_dict['a']

In [ ]:
a_tuple[1]

<div class="alert alert-info">
    <b>REMEMBER</b>: 
    <ul>
        <li> [] for accessing elements
    </ul>
</div>

Assigning new values to items -> `mutable` vs `immutable`

In [ ]:
a_list

In [ ]:
a_list[2] = 10 # element 2 changed -- mutable
a_list

In [ ]:
## TRY these yourself by un-commenting
#a_tuple[1] = 10 # cfr. a_string -- immutable
#a_string[3] = 'q'

## Control flows

### for-loop

In [ ]:
for i in [1, 2, 3, 4]:
    print(i)

In [ ]:
for i in a_list: # anything that is a collection/container can be looped
    print(i)

In [164]:
hello_str = "Hello DS"
for stub in hello_str.split(" "):
    print(stub)
    

for charact in hello_str:
    print(charact)

Hello
DS
H
e
l
l
o
 
D
S


<div class="alert alert-success">
    <b>EXERCISE</b>: Loop through the characters of the string `Hello DS` and print each character on a new line
</div>

In [ ]:
# %load _solutions/python_rehearsal62.py

In [ ]:
for i in a_dict: # items, keys, values
    print(i)

In [ ]:
for j, key in enumerate(a_dict.keys()):
    print(j, key)

<div class="alert alert-info">
    <b>REMEMBER</b>: When needing a iterator to count, just use `enumerate`. you mostly do not need i = 0 for... i = i +1.  
    Check [itertools](http://pymotw.com/2/itertools/) as well...
</div>

### while

In [ ]:
b = 7
while b < 10:
    b+=1
    print(b)

### if statement

In [ ]:
if 'a' in a_dict:
    print('a is in!')

In [ ]:
if 3 > 4:
    print('This is valid')

In [ ]:
testvalue = True  # 0, 1, None, False, 4 > 3
if testvalue:
    print('valid')
else:
    raise Exception("Not valid!")

In [ ]:
myvalue = 3
if isinstance(myvalue, str):
    print('this is a string')
elif isinstance(myvalue, float):
    print('this is a float')
elif isinstance(myvalue, list):
    print('this is a list')
else:
    print('no idea actually')

## Functions

We've been using functions the whole time...

In [ ]:
len(a_list)

Calling a method on an object:

In [ ]:
a_list.reverse()
a_list

Defining a function:

In [ ]:
def f(a, b, verbose=False):
    """custom summation function
    
    Parameters
    ----------
    a : number
        first number to sum
    b : number
        second number to sum   
    verbose: boolean
        require additional information (True) or not (False)
    
    Returns
    -------
    my_sum : number
        sum of the provided two input elements
    """
    
    if verbose:
        print('print a lot of information to the user')
        
    my_sum = a + b    
    
    return my_sum

In [ ]:
f(2, 3, verbose=False)  # [3], '4'


<div class="alert alert-info">
    <b>REMEMBER</b>: () for calling functions
</div>

**Functions are objects** as well... (!)

In [ ]:
def f1():
    print('this is function 1 speaking...')

def f2():
    print('this is function 2 speaking...')

In [ ]:
def function_of_functions(inputfunction):
    return inputfunction()

In [ ]:
function_of_functions(f1)

**Anonymous functions (lambda)**

In [ ]:
add_two = (lambda x: x + 2)

In [ ]:
add_two(10)

## Numpy

In [165]:
import numpy as np

### Creating numpy array

In [173]:
my_array = np.array([1, 1.5, 2, 2.5])  #np.array(anylist)
my_array.shape

(4,)

In [167]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [174]:
np.linspace(5, 9, 3)

array([ 5.,  7.,  9.])

In [175]:
np.zeros((5, 2)), np.ones(5)

(array([[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]), array([ 1.,  1.,  1.,  1.,  1.]))

In [176]:
np.zeros((5, 2)).shape, np.zeros((5, 2)).size

((5, 2), 10)

### Slicing

In [177]:
my_array = np.random.randint(2, 10, 10)
my_array

array([9, 3, 4, 5, 8, 9, 4, 3, 6, 8])

In [178]:
my_array[-2:]

array([6, 8])

In [179]:
my_array[0:7:2]

array([9, 4, 8, 4])

Assign new values to items

In [180]:
my_array[:2] = 10
my_array

array([10, 10,  4,  5,  8,  9,  4,  3,  6,  8])

In [181]:
my_array = my_array.reshape(5, 2)
my_array

array([[10, 10],
       [ 4,  5],
       [ 8,  9],
       [ 4,  3],
       [ 6,  8]])

In [182]:
my_array[0, :]

array([10, 10])

### Element-wise operations

In [183]:
my_array = np.random.randint(2, 10, 10)
print(my_array)

[8 9 8 2 8 4 5 2 3 5]


In [184]:
my_array%3  # == 0

array([2, 0, 2, 2, 2, 1, 2, 2, 0, 2], dtype=int32)

In [185]:
np.exp(my_array), np.sin(my_array)

(array([  2.98095799e+03,   8.10308393e+03,   2.98095799e+03,
          7.38905610e+00,   2.98095799e+03,   5.45981500e+01,
          1.48413159e+02,   7.38905610e+00,   2.00855369e+01,
          1.48413159e+02]),
 array([ 0.98935825,  0.41211849,  0.98935825,  0.90929743,  0.98935825,
        -0.7568025 , -0.95892427,  0.90929743,  0.14112001, -0.95892427]))

In [186]:
np.max(my_array)

9

In [187]:
np.cumsum(my_array) == my_array.cumsum()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [188]:
my_array.max(axis=0)

9

In [189]:
my_array * my_array  # element-wise

array([64, 81, 64,  4, 64, 16, 25,  4,  9, 25])

<div class="alert alert-info">
    <b>REMEMBER</b>: The operations do work on all elements of the array at the same time, you don't need a <strike>`for` loop<strike>
</div>

In [190]:
a_list = range(1000)
%timeit [i**2 for i in a_list]

373 µs ± 5.79 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [191]:
an_array = np.arange(1000)
%timeit an_array**2

1.71 µs ± 79.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Boolean indexing and filtering (!)

In [192]:
row_array = np.random.randint(1, 20, 10)
row_array

array([12, 11,  9, 14,  2,  1,  5,  8,  9,  2])

Conditions can be checked (element-wise):

In [193]:
row_array > 5

array([ True,  True,  True,  True, False, False, False,  True,  True, False], dtype=bool)

In [194]:
boolean_mask = row_array > 5

You can use this as a filter to select elements of an array:

In [195]:
row_array[boolean_mask]

array([12, 11,  9, 14,  8,  9])

or, also to change the values in the array corresponding to these conditions:

In [196]:
row_array[boolean_mask] = 20
row_array

array([20, 20, 20, 20,  2,  1,  5, 20, 20,  2])

in short - making the values equal to 20 now -20:

In [197]:
row_array[row_array == 20] = -20
row_array

array([-20, -20, -20, -20,   2,   1,   5, -20, -20,   2])

This requires some practice...

In [209]:
AR = np.random.randint(0, 20, 15)
AR

array([17, 13,  8,  2,  8,  7,  4, 12,  3,  4,  1,  6, 19, 11,  0])

<div class="alert alert-success">
    <b>EXERCISE</b>: Count the number of values in AR that are larger than 10 (note: you can count with True = 1 and False = 0)
</div>

In [214]:
sum(AR>10)
# %load _solutions/python_rehearsal107.py

array([False, False,  True,  True,  True, False,  True,  True, False,
        True, False,  True, False, False,  True], dtype=bool)

<div class="alert alert-success">
    <b>EXERCISE</b>: Change all even numbers of `AR` into zero-values.
</div>

In [215]:
AR[AR%2 == 0] = 0
AR
# %load _solutions/python_rehearsal108.py

array([17, 13,  0,  0,  0,  7,  0,  0,  3,  0,  1,  0, 19, 11,  0])

<div class="alert alert-success">
    <b>EXERCISE</b>: Change all even positions of matrix AR into the value 30
</div>

In [236]:
AR[np.arange(len(AR))%2 == 0] = 30
AR
# %load _solutions/python_rehearsal109.py

array([30, 13, 30,  0, 30,  7, 30,  0, 30,  0, 30,  0, 30, 11, 30])

<div class="alert alert-success">
    <b>EXERCISE</b>: Select all values above the 75th percentile of the following array AR2 ad take the square root of these values
</div>

In [244]:
AR2 = np.random.random(10)
AR2
AR2[AR2 > np.percentile(AR2, 75)]**2

array([ 0.68347546,  0.82149285,  0.67151827])

In [238]:
# %load _solutions/python_rehearsal111.py

<div class="alert alert-success">
    <b>EXERCISE</b>: Convert all values -99 of the array AR3 into Nan-values (Note that Nan values can be provided in float arrays as `np.nan` and that numpy provides a specialized function to compare float values, i.e. `np.isclose()`)
</div>

In [250]:
AR3 = np.array([-99., 2., 3., 6., 8, -99., 7., 5., 6., -99.])
AR3[AR3 == -99] = np.nan
AR3

array([ nan,   2.,   3.,   6.,   8.,  nan,   7.,   5.,   6.,  nan])

In [253]:
# Alternative solution with np.isclose()
AR3 = np.array([-99., 2., 3., 6., 8, -99., 7., 5., 6., -99.])
AR3[np.isclose(AR3, -99)] = np.nan
AR3

array([ nan,   2.,   3.,   6.,   8.,  nan,   7.,   5.,   6.,  nan])

In [254]:
# %load _solutions/python_rehearsal113.py

Ready for some real **Pandas!**